#!/bin/bash
# check and log if a host is reachable by ping

#CONFIGURATION

#IP of host
WATCH_IP="marbel-pc"
#path to logfile
LOGFILE="/var/log/watchip.log"
#duration between pings
PAUSE=3
#how many failed pings before log
TESTS=2

#SCRIPT

#initialize
MISSED=0
touch $LOGFILE

while true; do
  if ! ping -c 1 -w 1 $WATCH_IP > /dev/null; then
    ((MISSED++))
  else
    if [ $MISSED -ge $TESTS ]; then
      echo `date` '-' $WATCH_IP "is up again." >> $LOGFILE;
	/usr/local/src/raspberry-remote/send 11111 2 1;
  fi
    MISSED=0
  fi;
  if [ $MISSED -eq $TESTS ]; then
    echo `date` "-" $WATCH_IP "is down." >> $LOGFILE;
	/usr/local/src/raspberry-remote/send 11111 2 0;
  fi
  sleep $PAUSE;
done
